# 这个会被所有应用读取到，用来做公共配置
spring:
  rabbitmq:
    host: 192.168.99.101
    username: admin
    # 密文需要以{cipher}做为标识
    password: '{cipher}bc90211fd001384166db376d6c3a2af9db99377b1acf5fe13fe7f69a34200c5a'
tony:
  applicationText: 这是这是开发环境公共配置 
